### ISSUE TITLE
Download and clean data

### ISSUE THREAD

**Issue by nadialucas** [nadialucas/laura_epic_task#1]
To start this data project, I would like for you to download some data. To do this, complete the following steps:
1. Using the Python module, I would like you to download all the data from [this webpage](http://www.jasmiths.com/data_project). 
2. From there, use Stata (or your language of choice) to combine all of the data files. 
3.  Create a `statefips` variable, which is comprised of the first two digits of `fips`. This `statefips` variable corresponds to the [ANSI's codes](https://www.census.gov/geo/reference/ansi_statetables.html) for classifying states.
4.  Save this file as `superfund_sample`

**Comment by lalcocer** [comment]
Hi, I finished this task. Here's the copy of the code: https://github.com/nadialucas/laura_epic_task/tree/4dc2b3399a97e84664c7a99147f72a368cea7d24
