### ISSUE TITLE
Analyze the Data

### ISSUE THREAD

**Issue by nadialucas** [nadialucas/laura_epic_task#3]
As mentioned, we are interested in measuring the impact that the Superfund cleanup had on local housing prices. Specifically we would like to observe the relationship between a locale's 2000 log median house prices  (which I'll now call `lnmdvalhs0`) and its NPL status in 2000 (`npl2000`). Using your newly created `superfund_sample`, I would like you to run the following regressions:

1.  Regress `lnmdvalhs0` onto `npl2000`, using a price control
2.  Regress `lnmdvalhs0` onto `npl2000`, using price and house controls
3.  Regress `lnmdvalhs0` onto `npl2000`, using price, house, and economic controls
4. Lastly, regress `lnmdvalhs0` onto `npl2000`, using price, house, and economic controls. Use a `statefips` fixed effect. 

**Note:** for all of these regressions, use a se correction that’s robust to heteroskedasticity (i.e. [robust standard errors](https://economictheoryblog.com/2016/08/07/robust-standard-errors/))

Upon running these regressions, I'd like you to export them into a LaTeX table. For clarity, I only want to see the coefficient on `npl2000`, and if you used a price/house/economic control, or state fixed effects, include a "Yes" or "No" in the column. Ensure that your table is clear by using the variable labels and including helpful notes (when necessary). 

After completing all of this, report some brief findings from your regressions.

**Controls**
1. price: 1980 log mean house price (did you call it `lnmeanhs8`?)
2. house: `firestoveheat80`, `noaircond80`, `nofullkitchen80`, `zerofullbath80`, `bedrms0_80occ`, `bedrms1_80occ`, `bedrms2_80occ`, `bedrms3_80occ`, `bedrms4_80occ`, `bedrms5_80occ`, `blt0_1yrs80occ`, `blt2_5yrs80occ`, `blt6_10yrs80occ`, `blt10_20yrs80occ`, `blt20_30yrs80occ`, `blt30_40yrs80occ`, `blt40_yrs80occ`, `detach80occ`, and `mobile80occ` 
3. economic: `pop_den8`, `shrblk8`, `shrhsp8`, `child8`, `old8`, `shrfor8`, `ffh8`, `smhse8`, `hsdrop8`, `no_hs_diploma8`, `ba_or_better8`, `unemprt8`, `povrat8`, `welfare8`, `avhhin8`, `tothsun8`, `ownocc8`, and `occupied80`

**Comment by lalcocer** [comment]
Done with task, here's the link: https://github.com/nadialucas/laura_epic_task/tree/522295ac962d9732a65d5f81bfcc446a49090a87
